export const RESOURCES = [
  {
    key: 'categories',
    label: 'Categories',
    type: 'single',
    idKeys: ['CategoryID'],
    canUpdate: true,
  },
  {
    key: 'suppliers',
    label: 'Suppliers',
    type: 'single',
    idKeys: ['SupplierID'],
    canUpdate: true,
  },
  {
    key: 'shippers',
    label: 'Shippers',
    type: 'single',
    idKeys: ['ShipperID'],
    canUpdate: true,
  },
  { key: 'region', label: 'Region', type: 'single', idKeys: ['RegionID'], canUpdate: true },
  {
    key: 'customerdemographics',
    label: 'CustomerDemographics',
    type: 'single',
    idKeys: ['CustomerTypeID'],
    canUpdate: true,
  },
  { key: 'products', label: 'Products', type: 'single', idKeys: ['ProductID'], canUpdate: true },
  {
    key: 'territories',
    label: 'Territories',
    type: 'single',
    idKeys: ['TerritoryID'],
    canUpdate: true,
  },
  { key: 'customers', label: 'Customers', type: 'single', idKeys: ['CustomerID'], canUpdate: true },
  { key: 'employees', label: 'Employees', type: 'single', idKeys: ['EmployeeID'], canUpdate: true },
  { key: 'orders', label: 'Orders', type: 'single', idKeys: ['OrderID'], canUpdate: true },
  {
    key: 'order-details',
    label: 'OrderDetails',
    type: 'composite',
    idKeys: ['orderId', 'productId'],
    canUpdate: true,
  },
  {
    key: 'customer-customer-demo',
    label: 'CustomerCustomerDemo',
    type: 'composite',
    idKeys: ['customerId', 'customerTypeId'],
    canUpdate: false,
  },
  {
    key: 'employee-territories',
    label: 'EmployeeTerritories',
    type: 'composite',
    idKeys: ['employeeId', 'territoryId'],
    canUpdate: false,
  },
]
