export const RESOURCES = [
  {
    key: 'categories',
    label: 'Categories',
    type: 'single',
    idKeys: ['CategoryID'],
    canUpdate: true,
    formFields: ['CategoryName', 'Description'],
  },
  {
    key: 'suppliers',
    label: 'Suppliers',
    type: 'single',
    idKeys: ['SupplierID'],
    canUpdate: true,
    formFields: [
      'CompanyName',
      'ContactName',
      'ContactTitle',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'Phone',
      'Fax',
      'HomePage',
    ],
  },
  {
    key: 'shippers',
    label: 'Shippers',
    type: 'single',
    idKeys: ['ShipperID'],
    canUpdate: true,
    formFields: ['CompanyName', 'Phone'],
  },
  {
    key: 'region',
    label: 'Region',
    type: 'single',
    idKeys: ['RegionID'],
    canUpdate: true,
    formFields: ['RegionID', 'RegionDescription'],
  },
  {
    key: 'customerdemographics',
    label: 'CustomerDemographics',
    type: 'single',
    idKeys: ['CustomerTypeID'],
    canUpdate: true,
    formFields: ['CustomerTypeID', 'CustomerDesc'],
  },
  {
    key: 'products',
    label: 'Products',
    type: 'single',
    idKeys: ['ProductID'],
    canUpdate: true,
    formFields: [
      'ProductName',
      'SupplierID',
      'CategoryID',
      'QuantityPerUnit',
      'UnitPrice',
      'UnitsInStock',
      'UnitsOnOrder',
      'ReorderLevel',
      'Discontinued',
    ],
    foreignKeys: {
      SupplierID: {
        resourceKey: 'suppliers',
        valueKey: 'SupplierID',
        labelKey: 'CompanyName',
      },
      CategoryID: {
        resourceKey: 'categories',
        valueKey: 'CategoryID',
        labelKey: 'CategoryName',
      },
    },
  },
  {
    key: 'territories',
    label: 'Territories',
    type: 'single',
    idKeys: ['TerritoryID'],
    canUpdate: true,
    formFields: ['TerritoryID', 'TerritoryDescription', 'RegionID'],
    foreignKeys: {
      RegionID: {
        resourceKey: 'region',
        valueKey: 'RegionID',
        labelKey: 'RegionDescription',
      },
    },
  },
  {
    key: 'customers',
    label: 'Customers',
    type: 'single',
    idKeys: ['CustomerID'],
    canUpdate: true,
    formFields: [
      'CustomerID',
      'CompanyName',
      'ContactName',
      'ContactTitle',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'Phone',
      'Fax',
    ],
  },
  {
    key: 'employees',
    label: 'Employees',
    type: 'single',
    idKeys: ['EmployeeID'],
    canUpdate: true,
    formFields: [
      'LastName',
      'FirstName',
      'Title',
      'TitleOfCourtesy',
      'BirthDate',
      'HireDate',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'HomePhone',
      'Extension',
      'Notes',
      'ReportsTo',
      'PhotoPath',
    ],
    foreignKeys: {
      ReportsTo: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
    },
  },
  {
    key: 'orders',
    label: 'Orders',
    type: 'single',
    idKeys: ['OrderID'],
    canUpdate: true,
    formFields: [
      'CustomerID',
      'EmployeeID',
      'OrderDate',
      'RequiredDate',
      'ShippedDate',
      'ShipVia',
      'Freight',
      'ShipName',
      'ShipAddress',
      'ShipCity',
      'ShipRegion',
      'ShipPostalCode',
      'ShipCountry',
    ],
    foreignKeys: {
      CustomerID: {
        resourceKey: 'customers',
        valueKey: 'CustomerID',
        labelKey: 'CompanyName',
      },
      EmployeeID: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
      ShipVia: {
        resourceKey: 'shippers',
        valueKey: 'ShipperID',
        labelKey: 'CompanyName',
      },
    },
  },
  {
    key: 'order-details',
    label: 'OrderDetails',
    type: 'composite',
    idKeys: ['OrderID', 'ProductID'],
    canUpdate: true,
    formFields: ['OrderID', 'ProductID', 'UnitPrice', 'Quantity', 'Discount'],
    foreignKeys: {
      OrderID: {
        resourceKey: 'orders',
        valueKey: 'OrderID',
        labelKey: 'ShipName',
      },
      ProductID: {
        resourceKey: 'products',
        valueKey: 'ProductID',
        labelKey: 'ProductName',
      },
    },
  },
  {
    key: 'customer-customer-demo',
    label: 'CustomerCustomerDemo',
    type: 'composite',
    idKeys: ['CustomerID', 'CustomerTypeID'],
    canUpdate: false,
    formFields: ['CustomerID', 'CustomerTypeID'],
    foreignKeys: {
      CustomerID: {
        resourceKey: 'customers',
        valueKey: 'CustomerID',
        labelKey: 'CompanyName',
      },
      CustomerTypeID: {
        resourceKey: 'customerdemographics',
        valueKey: 'CustomerTypeID',
        labelKey: 'CustomerDesc',
      },
    },
  },
  {
    key: 'employee-territories',
    label: 'EmployeeTerritories',
    type: 'composite',
    idKeys: ['EmployeeID', 'TerritoryID'],
    canUpdate: false,
    formFields: ['EmployeeID', 'TerritoryID'],
    foreignKeys: {
      EmployeeID: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
      TerritoryID: {
        resourceKey: 'territories',
        valueKey: 'TerritoryID',
        labelKey: 'TerritoryDescription',
      },
    },
  },
]
