export const RESOURCES = [
  {
    key: 'categories',
    label: 'Categorias',
    type: 'single',
    idKeys: ['CategoryID'],
    canUpdate: true,
    formFields: ['CategoryID', 'CategoryName', 'Description'],
    fieldLabels: {
      CategoryID: 'ID de categoria',
      CategoryName: 'Nombre de categoria',
      Description: 'Descripcion',
    },
    fieldTypes: {
      CategoryID: 'number',
      CategoryName: 'text',
      Description: 'textarea',
    },
  },
  {
    key: 'suppliers',
    label: 'Proveedores',
    type: 'single',
    idKeys: ['SupplierID'],
    canUpdate: true,
    formFields: [
      'SupplierID',
      'CompanyName',
      'ContactName',
      'ContactTitle',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'Phone',
      'Fax',
      'HomePage',
    ],
    fieldLabels: {
      SupplierID: 'ID de proveedor',
      CompanyName: 'Empresa',
      ContactName: 'Contacto',
      ContactTitle: 'Cargo del contacto',
      Address: 'Direccion',
      City: 'Ciudad',
      Region: 'Region',
      PostalCode: 'Codigo postal',
      Country: 'Pais',
      Phone: 'Telefono',
      Fax: 'Fax',
      HomePage: 'Sitio web',
    },
    fieldTypes: {
      SupplierID: 'number',
      HomePage: 'textarea',
    },
  },
  {
    key: 'shippers',
    label: 'Transportistas',
    type: 'single',
    idKeys: ['ShipperID'],
    canUpdate: true,
    formFields: ['ShipperID', 'CompanyName', 'Phone'],
    fieldLabels: {
      ShipperID: 'ID de transportista',
      CompanyName: 'Empresa',
      Phone: 'Telefono',
    },
    fieldTypes: {
      ShipperID: 'number',
    },
  },
  {
    key: 'region',
    label: 'Regiones',
    type: 'single',
    idKeys: ['RegionID'],
    canUpdate: true,
    formFields: ['RegionID', 'RegionDescription'],
    fieldLabels: {
      RegionID: 'ID de region',
      RegionDescription: 'Nombre de region',
    },
    fieldTypes: {
      RegionID: 'number',
    },
  },
  {
    key: 'customerdemographics',
    label: 'Tipos de Cliente',
    type: 'single',
    idKeys: ['CustomerTypeID'],
    canUpdate: true,
    formFields: ['CustomerTypeID', 'CustomerDesc'],
    fieldLabels: {
      CustomerTypeID: 'ID de tipo de cliente',
      CustomerDesc: 'Descripcion del tipo',
    },
    fieldTypes: {
      CustomerDesc: 'textarea',
    },
  },
  {
    key: 'products',
    label: 'Productos',
    type: 'single',
    idKeys: ['ProductID'],
    canUpdate: true,
    formFields: [
      'ProductID',
      'ProductName',
      'SupplierID',
      'CategoryID',
      'QuantityPerUnit',
      'UnitPrice',
      'UnitsInStock',
      'UnitsOnOrder',
      'ReorderLevel',
      'Discontinued',
    ],
    fieldLabels: {
      ProductID: 'ID de producto',
      ProductName: 'Nombre del producto',
      SupplierID: 'Proveedor',
      CategoryID: 'Categoria',
      QuantityPerUnit: 'Cantidad por unidad',
      UnitPrice: 'Precio unitario',
      UnitsInStock: 'Unidades en stock',
      UnitsOnOrder: 'Unidades en pedido',
      ReorderLevel: 'Nivel de reorden',
      Discontinued: 'Descontinuado',
    },
    fieldTypes: {
      ProductID: 'number',
      SupplierID: 'number',
      CategoryID: 'number',
      UnitPrice: 'number',
      UnitsInStock: 'number',
      UnitsOnOrder: 'number',
      ReorderLevel: 'number',
      Discontinued: 'checkbox',
    },
    foreignKeys: {
      SupplierID: {
        resourceKey: 'suppliers',
        valueKey: 'SupplierID',
        labelKey: 'CompanyName',
      },
      CategoryID: {
        resourceKey: 'categories',
        valueKey: 'CategoryID',
        labelKey: 'CategoryName',
      },
    },
  },
  {
    key: 'territories',
    label: 'Territorios',
    type: 'single',
    idKeys: ['TerritoryID'],
    canUpdate: true,
    formFields: ['TerritoryID', 'TerritoryDescription', 'RegionID'],
    fieldLabels: {
      TerritoryID: 'ID de territorio',
      TerritoryDescription: 'Nombre de territorio',
      RegionID: 'Region',
    },
    fieldTypes: {
      RegionID: 'number',
    },
    foreignKeys: {
      RegionID: {
        resourceKey: 'region',
        valueKey: 'RegionID',
        labelKey: 'RegionDescription',
      },
    },
  },
  {
    key: 'customers',
    label: 'Clientes',
    type: 'single',
    idKeys: ['CustomerID'],
    canUpdate: true,
    formFields: [
      'CustomerID',
      'CompanyName',
      'ContactName',
      'ContactTitle',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'Phone',
      'Fax',
    ],
    fieldLabels: {
      CustomerID: 'ID de cliente',
      CompanyName: 'Empresa',
      ContactName: 'Contacto',
      ContactTitle: 'Cargo del contacto',
      Address: 'Direccion',
      City: 'Ciudad',
      Region: 'Region',
      PostalCode: 'Codigo postal',
      Country: 'Pais',
      Phone: 'Telefono',
      Fax: 'Fax',
    },
  },
  {
    key: 'employees',
    label: 'Empleados',
    type: 'single',
    idKeys: ['EmployeeID'],
    canUpdate: true,
    formFields: [
      'EmployeeID',
      'LastName',
      'FirstName',
      'Title',
      'TitleOfCourtesy',
      'BirthDate',
      'HireDate',
      'Address',
      'City',
      'Region',
      'PostalCode',
      'Country',
      'HomePhone',
      'Extension',
      'Notes',
      'ReportsTo',
      'PhotoPath',
    ],
    fieldLabels: {
      EmployeeID: 'ID de empleado',
      LastName: 'Apellidos',
      FirstName: 'Nombres',
      Title: 'Puesto',
      TitleOfCourtesy: 'Cortesia',
      BirthDate: 'Fecha de nacimiento',
      HireDate: 'Fecha de contratacion',
      Address: 'Direccion',
      City: 'Ciudad',
      Region: 'Region',
      PostalCode: 'Codigo postal',
      Country: 'Pais',
      HomePhone: 'Telefono',
      Extension: 'Extension',
      Notes: 'Notas',
      ReportsTo: 'Reporta a',
      PhotoPath: 'Ruta de foto',
    },
    fieldTypes: {
      EmployeeID: 'number',
      BirthDate: 'datetime-local',
      HireDate: 'datetime-local',
      Notes: 'textarea',
      ReportsTo: 'number',
    },
    foreignKeys: {
      ReportsTo: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
    },
  },
  {
    key: 'orders',
    label: 'Pedidos',
    type: 'single',
    idKeys: ['OrderID'],
    canUpdate: true,
    formFields: [
      'OrderID',
      'CustomerID',
      'EmployeeID',
      'OrderDate',
      'RequiredDate',
      'ShippedDate',
      'ShipVia',
      'Freight',
      'ShipName',
      'ShipAddress',
      'ShipCity',
      'ShipRegion',
      'ShipPostalCode',
      'ShipCountry',
    ],
    fieldLabels: {
      OrderID: 'ID de pedido',
      CustomerID: 'Cliente',
      EmployeeID: 'Empleado',
      OrderDate: 'Fecha de pedido',
      RequiredDate: 'Fecha requerida',
      ShippedDate: 'Fecha de envio',
      ShipVia: 'Transportista',
      Freight: 'Flete',
      ShipName: 'Destinatario',
      ShipAddress: 'Direccion de envio',
      ShipCity: 'Ciudad de envio',
      ShipRegion: 'Region de envio',
      ShipPostalCode: 'Codigo postal de envio',
      ShipCountry: 'Pais de envio',
    },
    fieldTypes: {
      OrderID: 'number',
      EmployeeID: 'number',
      ShipVia: 'number',
      OrderDate: 'datetime-local',
      RequiredDate: 'datetime-local',
      ShippedDate: 'datetime-local',
      Freight: 'number',
    },
    foreignKeys: {
      CustomerID: {
        resourceKey: 'customers',
        valueKey: 'CustomerID',
        labelKey: 'CompanyName',
      },
      EmployeeID: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
      ShipVia: {
        resourceKey: 'shippers',
        valueKey: 'ShipperID',
        labelKey: 'CompanyName',
      },
    },
  },
  {
    key: 'order-details',
    label: 'Detalle de Pedidos',
    type: 'composite',
    idKeys: ['OrderID', 'ProductID'],
    canUpdate: true,
    formFields: ['OrderID', 'ProductID', 'UnitPrice', 'Quantity', 'Discount'],
    fieldLabels: {
      OrderID: 'Pedido',
      ProductID: 'Producto',
      UnitPrice: 'Precio unitario',
      Quantity: 'Cantidad',
      Discount: 'Descuento',
    },
    fieldTypes: {
      OrderID: 'number',
      ProductID: 'number',
      UnitPrice: 'number',
      Quantity: 'number',
      Discount: 'number',
    },
    foreignKeys: {
      OrderID: {
        resourceKey: 'orders',
        valueKey: 'OrderID',
        labelKey: 'ShipName',
      },
      ProductID: {
        resourceKey: 'products',
        valueKey: 'ProductID',
        labelKey: 'ProductName',
      },
    },
  },
  {
    key: 'customer-customer-demo',
    label: 'Relacion Cliente-Segmento',
    type: 'composite',
    idKeys: ['CustomerID', 'CustomerTypeID'],
    canUpdate: false,
    formFields: ['CustomerID', 'CustomerTypeID'],
    fieldLabels: {
      CustomerID: 'Cliente',
      CustomerTypeID: 'Tipo de cliente',
    },
    foreignKeys: {
      CustomerID: {
        resourceKey: 'customers',
        valueKey: 'CustomerID',
        labelKey: 'CompanyName',
      },
      CustomerTypeID: {
        resourceKey: 'customerdemographics',
        valueKey: 'CustomerTypeID',
        labelKey: 'CustomerDesc',
      },
    },
  },
  {
    key: 'employee-territories',
    label: 'Relacion Empleado-Territorio',
    type: 'composite',
    idKeys: ['EmployeeID', 'TerritoryID'],
    canUpdate: false,
    formFields: ['EmployeeID', 'TerritoryID'],
    fieldLabels: {
      EmployeeID: 'Empleado',
      TerritoryID: 'Territorio',
    },
    foreignKeys: {
      EmployeeID: {
        resourceKey: 'employees',
        valueKey: 'EmployeeID',
        labelKey: 'LastName',
      },
      TerritoryID: {
        resourceKey: 'territories',
        valueKey: 'TerritoryID',
        labelKey: 'TerritoryDescription',
      },
    },
  },
]
